### ISSUE TITLE
无法上传图片，一直转圈，console提示有错误

### ISSUE THREAD

**Issue by JNULYD** [wtx358/flask-ueditor-demo#2]
下载下来之后安装好环境后运行，无法上传文件，console控制台提示有错误：
ueditor.all.min.js:545 Uncaught ReferenceError: errorHandler is not defined
    at HTMLInputElement.<anonymous> (ueditor.all.min.js:545)

不知道哪里 有错误呢？

**Comment by wtx358** [comment]
不好意思，我这边没有出现类似的提示

**Comment by zhangming0922** [comment]
相同的错误

**Comment by zhangming0922** [comment]
fix:
# 解析JSON格式的配置文件
    config_path = os.path.join(app.static_folder, 'ueditor', 'php', 'config.json')
    with open(config_path, 'r', encoding='utf-8') as fp:
        CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))

    # 初始化时返回配置信息
    if action == 'config':
        result = CONFIG

**Comment by wtx358** [comment]
> fix:
> 
> # 解析JSON格式的配置文件
> ```
> config_path = os.path.join(app.static_folder, 'ueditor', 'php', 'config.json')
> with open(config_path, 'r', encoding='utf-8') as fp:
>     CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))
> 
> # 初始化时返回配置信息
> if action == 'config':
>     result = CONFIG
> ```

Python版本是多少，之前只在2.7下面测试过

**Comment by wtx358** [comment]
这个示例之前只在 Python2.7 下测试过，如果是 Python3，请给 `open` 方法加上 `encoding='utf-8'` 参数

**Comment by JNULYD** [comment]
已经解决了，原来是因为 安全校验问题。编辑器的安全校验和flask的csrf token发生了冲突。取消编辑器的安全校验就可以正常上传图片了。
